### PR TITLE
updated respect library

### PR DESCRIPTION
**Pull request by gawonmi**

### CODE REVIEW

**Comment by anlutro** [comment]
Maybe you should've used the squash merge here :P

**Comment by gawonmi** [comment]
did not know that git command. ha....you learning something new every day. :)

**Comment by anlutro** [comment]
There was a button added to Github recently that lets you do it without involving the CLI. https://github.com/blog/2141-squash-your-commits

**Comment by gawonmi** [comment]
mhm...I did not see that button...did you enable it?

**Comment by anlutro** [comment]
Admittedly, I did not... though "Allow squash merging" is checked in the settings, so I think it's enabled by default.

**Pull request merged**
