### PR TITLE
Change share method to singleton. v5.4 fix

### PR DESCRIPTION
**Pull request by stojankukrika**
Change share method to singleton. laravel v5.4 fix

### CODE REVIEW

**Comment by anlutro** [comment]
Do you know if this works for all 5.x versions?

**Comment by stojankukrika** [comment]
this is addition in 5.4, maybe is the best make a new branch and make it different for older and newer version.

**Comment by anlutro** [comment]
I thought the `singleton` method had been around for a long time? Did its behaviour change?

**Comment by stojankukrika** [comment]
I think also but when try to install this package into new laravel 5.4 it shows me a problem. Google it and find that it solve that problem.I didn't try it with lower version but in 5.4 works great after this changes.

**Comment by stojankukrika** [comment]
Please publish it in some different branch or something to get that in composer... to didn't need to change it every time when run composer install.Because that change is work in laravel 5.4+ (I try in new 5.5 also)

**Comment by anlutro** [comment]
Sorry for taking ages on this, I only recently realized I could use `version_compare` to solve this without breaking anything. Will tag a new release soon.

**Pull request closed without merging**
