### PR TITLE
added support for get_status and some other tweajs

### PR DESCRIPTION
**Pull request by gawonmi**
- Added injection of base url
- Added tests for bulksms
- Added support for get_status
- Added support for codeception
- added some additional validations 

Don't use laravel, so cannot test if it works in the framework

### CODE REVIEW

**Comment by anlutro** [comment]
Wow, that's some solid work!

As you may have noticed I don't put any work into this anymore. Would you like me to add you as a comitter to this repository?

**Comment by gawonmi** [comment]
will probably be doing some more cleanup work in the future, so yeah ;)

**Comment by anlutro** [comment]
Awesome! I'm currently on vacation but will have a quick look at this on
Friday or Saturday.

**Comment by anlutro** [comment]
Cleaned up your commits a bit and made some further changes, but all of it is in the master branch now. I don't know to what degree you're using this library in live applications, but if you do, maybe you could check if it still works with the changes I made.

I also added you as a collaborator, so you should be able to push commits directly, though for anything other than tiny fixes/critical bugfixes we should branch and make a pull request.

**Pull request closed without merging**
