### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by gawonmi**
This pull request is in response to your last comment.

I basically just cleaned up up the files a bit more, corrected some mistakes, added a few sections to the readme and tested the rest in my application. 

The changes to config.php and the readme.txt in respects to laravel are assumptions. please verify.

I'd also propose to turn this into v1.3

### CODE REVIEW

**Comment by anlutro** [comment]
Awesome. When released, I'll just make it 2.0 because the changes are honestly too big and it's been too long since I worked with this that I can guarantee that it's backwards compatible.

It looks like some of the commits I squashed from your last PR made it back in, which is creating quite the mess. Am I correct in assuming [this commit](https://github.com/gawonmi/php-bulk-sms/commit/7ac28195587ba6441af2b88f1ad4f6be84dd4af2) is where all the important changes are made?

I suggest you do a `git remote update && git reset --hard origin/master` (if origin is the name of the remote for this repository) in order to sync your repository to this one. Maybe save your current master branch to a different branch in case you forgot some changes.

If, in the future, you always make sure to create branches for pull requests, you should have less problems with this sort of thing.

**Comment by gawonmi** [comment]
you are indeed correct. only the last one was supposed be there. shall I reset and recommit or do you want to integrate this pull request?

**Comment by anlutro** [comment]
I'll manually merge it, no worries.

**Comment by anlutro** [comment]
Commited https://github.com/gawonmi/php-bulk-sms/commit/7ac28195587ba6441af2b88f1ad4f6be84dd4af2 as https://github.com/anlutro/php-bulk-sms/commit/d0b8889afd68fb86b29095c9940a7d64ed879b12. You should be able to safely `git reset --hard origin/master` now.

**Comment by gawonmi** [comment]
confirmed

**Comment by anlutro** [comment]
I'll just go ahead and tag 2.0.0 then!

Thanks again for your work!

**Pull request closed without merging**
